### ISSUE TITLE
Exception in thread "main" com.cloudtemple.mattermost.traders.ApiV4Exception: 401 Invalid or expired session, please login again.

### ISSUE THREAD

**Issue by MSahal** [Cloud-Temple/Mattermost-client#1]
Exception in thread "main" com.cloudtemple.mattermost.traders.ApiV4Exception: 401 Invalid or expired session, please login again.

I cannot get any information even I am connected . 

[]
![bug](https://user-images.githubusercontent.com/3973597/35599904-6593346c-062b-11e8-85f0-c1cbc1b15187.jpg)

**Comment by Galigator** [comment]
This is a problem with your personal access token. If I provide an invalid personal access token I get the exact same error.

**Comment by MSahal** [comment]
What I did is that I generate a token for a user (I have only one user ) and I use it as token .

**Comment by Galigator** [comment]
Here 8 configurations steps that work for me using a Mattermost 4.1. Maybe it is possible to do something shorter, but this work.

1 ) create account  (Galigator)
2 ) create team
3 ) System console > Custom Integration > Enable personal token
4 ) System console > Signup > Enable Open Server > false
5 ) Team Settings > Allow an yser with an account on this server to join this team
6 ) System console > Users > (Galigator) > Manage Roles > Allow Personnal token > Post : All
7 ) Empty the browser cache
8 ) (Galigator) > Account Settings > Security > Personal Acces Token > Create new Token

**Comment by MSahal** [comment]
Finally it worked , I am using Mattermost 4.5 ... I just removed and reinstalled the mattermost instance in docker , and I followed the steps you described , and it's OK.
